<tt>
Oh,&nbsp;sorry,&nbsp;I&nbsp;misunderstood.&nbsp;If&nbsp;you&nbsp;want&nbsp;to&nbsp;throw&nbsp;an&nbsp;exception&nbsp;during&nbsp;reading/writing&nbsp;I&nbsp;believe&nbsp;that's&nbsp;fine&nbsp;(although&nbsp;I'm&nbsp;not&nbsp;100%&nbsp;sure&nbsp;there&nbsp;aren't&nbsp;edge&nbsp;cases&nbsp;I&nbsp;don't&nbsp;know&nbsp;about).&nbsp;Exact&nbsp;behavior&nbsp;likely&nbsp;depends&nbsp;on&nbsp;what&nbsp;functions&nbsp;are&nbsp;being&nbsp;used.&nbsp;The&nbsp;with_file&nbsp;functions&nbsp;of&nbsp;both&nbsp;Reader/Writer&nbsp;will,&nbsp;for&nbsp;example,&nbsp;close&nbsp;the&nbsp;files&nbsp;properly&nbsp;even&nbsp;if&nbsp;an&nbsp;exception&nbsp;is&nbsp;thrown&nbsp;in&nbsp;the&nbsp;function&nbsp;you&nbsp;pass&nbsp;it.
</tt>
